SET EAX 0
SET AX 7
SET SI 2
SET DI 14
SET BX 14
RESIZE 64
IO_FS_CREATE Int2 texto1.txt
IO_FS_TRUNCATE Int2 texto1.txt BX
IO_STDIN_READ Int1 EAX AX
IO_FS_WRITE Int2 texto1.txt EAX AX SI
IO_FS_READ Int2 texto1.txt EAX AX SI
EXIT 